fail_fast: true
repos:
  - repo: local
    hooks:
      - id: generate-idh-docs
        name: Generate IDH Docs
        entry: .scripts/generate-idh-docs.sh
        language: python
        types: [java] # use java as filter to avoid triggering this hook for other file types, since this is a terraform specific check and we don't want to run it for every file change
        always_run: true
      - id: check-variables-tf
        name: Check Terraform variables.tf conventions
        entry: .scripts/check-variables-tf.sh
        language: python
        types: [java] # use java as filter to avoid triggering this hook for other file types, since this is a terraform specific check and we don't want to run it for every file change
        always_run: true
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/mcole18/terraform-check-unused-variables.git
    rev: v1.2.1
    hooks:
      - id: check-unused-vars
        args: [ -r, -q, --dir=., --var-file=variables.tf ]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_docs
        args:
          - --args=--hide providers
      #validate will exclude folders that contains xyz/test... and .utils that contains only scripts stuffs
      - id: terraform_validate
        exclude: '(.*\/tests|.utils)'
        args:
          - --args=-json
          - --args=-no-color
