apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elastic-cloud-agent
subjects:
  - kind: ServiceAccount
    name: elastic-cloud-agent
    namespace: ${namespace}
roleRef:
  kind: ClusterRole
  name: elastic-cloud-agent
  apiGroup: rbac.authorization.k8s.io