apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ${namespace}
  name: elastic-cloud-agent
subjects:
  - kind: ServiceAccount
    name: elastic-cloud-agent
    namespace: ${namespace}
roleRef:
  kind: Role
  name: elastic-cloud-agent
  apiGroup: rbac.authorization.k8s.io