{
 "title": "${resource}",
 "tags": [
  "${prefix}",
  "auto_dashboard",
  "terraform"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "pagopa",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Storage Account - ${resource}\n"
   }
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Account Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "UsedCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "BlobCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "TableCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "FileCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "QueueCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Storage capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "BlobCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "TableCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "FileCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue Capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "QueueCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Storage count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "BlobCount",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Table Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "TableCount",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "FileCount",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue Count",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "QueueCount",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "PT5M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Ingress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Egress",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Transactions by storage type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "Table transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "Blob transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "File transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "Queue transactions",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Transactions by API Name",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Capacity by storage type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "",
      "alias": "Table capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "select",
      "resourceName": "select",
      "timeGrain": "",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Blob capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Blob type", "value": "BlobType" },
       { "text": "Blob tier", "value": "Tier" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "BlobCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "File capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "FileCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "alias": "Queue capacity",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "QueueCapacity",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Availability by storage type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Table availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Blob availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "File availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Queue availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Failures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ResponseType", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ResponseType", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Blob Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" },
       { "dimension": "ResponseType", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "File Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" },
       { "dimension": "ResponseType", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Table Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" },
       { "dimension": "ResponseType", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Queue Services",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" },
       { "dimension": "ResponseType", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "Transactions",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 60 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessE2ELatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "SuccessServerLatency",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "type": "gauge",
   "description": "The data comes from Storage metrics. It measures the availability of requests on Storage accounts.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Account Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Blob Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Table Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "File Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Queue Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Availability by API name",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resourceGroup": "${rg}",
      "resourceName": "${resource}/default",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  },
  {
   "title": "Availability Trend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Blob Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/blobServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/blobServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Table Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/tableServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "File Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" },
       { "text": "File Share", "value": "FileShare" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/fileServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/fileServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "00000000-0000-0000-0000-000000000000"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "Queue Availability",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
      "metricName": "Availability",
      "metricNamespace": "Microsoft.Storage/storageAccounts/queueServices",
      "resources": [
       { "resourceGroup": "${rg}", "resourceName": "${resource}/default" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "${sub}"
    }
   ]
  }
 ]
}