{
 "title": "${resource}",
 "description": "The dashboard provides insights of Azure Cosmos DB overview, throughput, requests, storage, availability latency, system and account management.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "sub", "label": "Subscription", "query": "subscriptions()" },
   { "name": "rg", "label": "Resource Group", "query": "ResourceGroups($sub)" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "Microsoft.DocumentDb/databaseAccounts"
   },
   { "name": "resource", "label": "Resource", "query": "ResourceNames($sub, $rg, $ns)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "$ns",
      "metricName": "TotalRequests",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throttled Requests (429s)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "StatusCode", "filters": [ "429" ], "operator": "eq" }
      ],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "$ns",
      "metricName": "TotalRequests",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resources": [
       { "resourceGroup": "$rg", "resourceName": "$resource" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Normalized RU Consumption (max)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" },
       { "text": "PartitionKeyRangeId", "value": "PartitionKeyRangeId" }
      ],
      "metricDefinition": "$ns",
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Index & Data Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "$ns",
      "metricName": "IndexUsage",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DataUsage",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Total Requests (Count) By Collection",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Count" ],
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "CollectionName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "Region", "value": "Region" },
       { "text": "StatusCode", "value": "StatusCode" },
       { "text": "OperationType", "value": "OperationType" },
       { "text": "Status", "value": "Status" }
      ],
      "metricDefinition": "$ns",
      "metricName": "TotalRequests",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Document Count (Avg) By Collection",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "CollectionName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DocumentCount",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Data Usage (Avg) By Collection",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "CollectionName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "$ns",
      "metricName": "DataUsage",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Index Usage (Avg) By Collection",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "CollectionName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" }
      ],
      "metricDefinition": "$ns",
      "metricName": "IndexUsage",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Provisioned Throughput (Max) By Collection",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [ "Maximum" ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       300000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "CollectionName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "CollectionName", "value": "CollectionName" }
      ],
      "metricDefinition": "$ns",
      "metricName": "ProvisionedThroughput",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "5 minutes", "value": "PT5M" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Normalized RU Consumption (Max) By Collection",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "azureMonitor": {
      "aggOptions": [
       "Maximum",
       "Average"
      ],
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [
       { "dimension": "CollectionName", "filter": "", "operator": "eq" }
      ],
      "dimensions": [
       { "text": "CollectionName", "value": "CollectionName" },
       { "text": "DatabaseName", "value": "DatabaseName" },
       { "text": "Region", "value": "Region" },
       { "text": "PartitionKeyRangeId", "value": "PartitionKeyRangeId" }
      ],
      "metricDefinition": "$ns",
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
      "resourceGroup": "$rg",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Request Units",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "StatusCode", "value": "StatusCode" },
         { "text": "OperationType", "value": "OperationType" },
         { "text": "Status", "value": "Status" }
        ],
        "metricDefinition": "$ns",
        "metricName": "TotalRequestUnits",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Normalized RU Consumption By PartitionKeyRangeID",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [
         "Maximum",
         "Average"
        ],
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         3600000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "PartitionKeyRangeId", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" },
         { "text": "PartitionKeyRangeId", "value": "PartitionKeyRangeId" }
        ],
        "metricDefinition": "$ns",
        "metricName": "NormalizedRUConsumption",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Provisioned Throughput (Max) by Collection",
     "type": "stat",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Maximum" ],
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "CollectionName", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" }
        ],
        "metricDefinition": "$ns",
        "metricName": "ProvisionedThroughput",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Requests by Status Code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "StatusCode", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "StatusCode", "value": "StatusCode" },
         { "text": "OperationType", "value": "OperationType" },
         { "text": "Status", "value": "Status" }
        ],
        "metricDefinition": "$ns",
        "metricName": "TotalRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Throttled Requests (429)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "StatusCode", "filter": "429", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "StatusCode", "value": "StatusCode" },
         { "text": "OperationType", "value": "OperationType" },
         { "text": "Status", "value": "Status" }
        ],
        "metricDefinition": "$ns",
        "metricName": "TotalRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Total Requests by Operation Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "OperationType", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "StatusCode", "value": "StatusCode" },
         { "text": "OperationType", "value": "OperationType" },
         { "text": "Status", "value": "Status" }
        ],
        "metricDefinition": "$ns",
        "metricName": "TotalRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Data & Index Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" }
        ],
        "metricDefinition": "$ns",
        "metricName": "DataUsage",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" }
        ],
        "metricDefinition": "$ns",
        "metricName": "IndexUsage",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Document Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" }
        ],
        "metricDefinition": "$ns",
        "metricName": "DocumentCount",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Data, Index & Document Usage",
     "type": "stat",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "CollectionName", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" }
        ],
        "metricDefinition": "$ns",
        "metricName": "DataUsage",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "CollectionName", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" }
        ],
        "metricDefinition": "$ns",
        "metricName": "IndexUsage",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Average"
        ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "CollectionName", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "Region", "value": "Region" }
        ],
        "metricDefinition": "$ns",
        "metricName": "DocumentCount",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "sub",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Service Availability (min/max/avg in %)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [
         "Minimum",
         "Average",
         "Maximum"
        ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         3600000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "ServiceAvailability",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 hour", "value": "PT1H" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [
         "Minimum",
         "Average",
         "Maximum"
        ],
        "aggregation": "Minimum",
        "allowedTimeGrainsMs": [
         3600000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "ServiceAvailability",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 hour", "value": "PT1H" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [
         "Minimum",
         "Average",
         "Maximum"
        ],
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         3600000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "ServiceAvailability",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 hour", "value": "PT1H" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Server Side Latency (Avg) By Region",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Average" ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "Region", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "ConnectionMode", "value": "ConnectionMode" },
         { "text": "OperationType", "value": "OperationType" },
         { "text": "PublicAPIType", "value": "PublicAPIType" }
        ],
        "metricDefinition": "$ns",
        "metricName": "ServerSideLatency",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Server Side Latency (Avg) By Operation",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Average" ],
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "OperationType", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "ConnectionMode", "value": "ConnectionMode" },
         { "text": "OperationType", "value": "OperationType" },
         { "text": "PublicAPIType", "value": "PublicAPIType" }
        ],
        "metricDefinition": "$ns",
        "metricName": "ServerSideLatency",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Metadata Requests by Status Code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "StatusCode", "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "StatusCode", "value": "StatusCode" }
        ],
        "metricDefinition": "$ns",
        "metricName": "MetadataRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Metadata Requests That Exceeded Capacity (429s)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "StatusCode", "filter": "429", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DatabaseName", "value": "DatabaseName" },
         { "text": "CollectionName", "value": "CollectionName" },
         { "text": "Region", "value": "Region" },
         { "text": "StatusCode", "value": "StatusCode" }
        ],
        "metricDefinition": "$ns",
        "metricName": "MetadataRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Account Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cosmos DB Account Management (Creates, Deletes) and Account Key Updates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "CreateAccount",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "DeleteAccount",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "KeyType", "value": "KeyType" }
        ],
        "metricDefinition": "$ns",
        "metricName": "UpdateAccountKeys",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Cosmos DB Account Diagnostic, Network and Replication Settings Updates",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [
         { "text": "DiagnosticSettings Name", "value": "DiagnosticSettingsName" },
         { "text": "ResourceGroup Name", "value": "ResourceGroupName" }
        ],
        "metricDefinition": "$ns",
        "metricName": "UpdateDiagnosticsSettings",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "UpdateAccountNetworkSettings",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      },
      {
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "filter": "", "operator": "eq" }
        ],
        "dimensions": [],
        "metricDefinition": "$ns",
        "metricName": "UpdateAccountReplicationSettings",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "5 minutes", "value": "PT5M" }
        ],
        "top": "10"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  }
 ]
}