apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:${receiver_port}
        
    processors:
      memory_limiter:
        check_interval: 1s
        limit_mib: 2000
      batch:

    exporters:
      logging:
        loglevel: warn

      otlphttp/elastic:
        tls:
          insecure: true
        endpoint: "${apm_endpoint}"
        headers:
          Authorization: "ApiKey ${apm_api_key}"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging, otlphttp/elastic]
        metrics:
          receivers: [otlp]
          exporters: [logging, otlphttp/elastic]
        logs: 
          receivers: [otlp]
          exporters: [logging, otlphttp/elastic]
