output "azure_client_id" {
  description = "The Application (client) ID generated by Azure"
  value       = azuread_application.keycloak.client_id
}

output "azure_client_secret" {
  description = "The Client Secret value generated by Azure"
  value       = azuread_application_password.client_secret.value
  sensitive   = true
}